# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_options_streaming_metadata.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StreamingMetadataOptionsPage(object):
    def setupUi(self, StreamingMetadataOptionsPage):
        StreamingMetadataOptionsPage.setObjectName("StreamingMetadataOptionsPage")
        StreamingMetadataOptionsPage.resize(400, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(StreamingMetadataOptionsPage.sizePolicy().hasHeightForWidth())
        StreamingMetadataOptionsPage.setSizePolicy(sizePolicy)
        StreamingMetadataOptionsPage.setWindowTitle("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(StreamingMetadataOptionsPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.enable_spotify = QtWidgets.QGroupBox(StreamingMetadataOptionsPage)
        self.enable_spotify.setCheckable(True)
        self.enable_spotify.setChecked(True)
        self.enable_spotify.setObjectName("enable_spotify")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.enable_spotify)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.enable_spotify)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.spotify_id = QtWidgets.QLineEdit(self.enable_spotify)
        self.spotify_id.setInputMask("")
        self.spotify_id.setText("")
        self.spotify_id.setObjectName("spotify_id")
        self.verticalLayout_4.addWidget(self.spotify_id)
        self.label_2 = QtWidgets.QLabel(self.enable_spotify)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.spotify_secret = QtWidgets.QLineEdit(self.enable_spotify)
        self.spotify_secret.setText("")
        self.spotify_secret.setEchoMode(QtWidgets.QLineEdit.Password)
        self.spotify_secret.setObjectName("spotify_secret")
        self.verticalLayout_4.addWidget(self.spotify_secret)
        self.verticalLayout_3.addWidget(self.enable_spotify)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)

        self.retranslateUi(StreamingMetadataOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(StreamingMetadataOptionsPage)

    def retranslateUi(self, StreamingMetadataOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.enable_spotify.setTitle(_translate("StreamingMetadataOptionsPage", "Spotify"))
        self.label.setText(_translate("StreamingMetadataOptionsPage", "Client ID:"))
        self.label_2.setText(_translate("StreamingMetadataOptionsPage", "Client secret:"))
