# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_options_streaming_metadata.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StreamingMetadataOptionsPage(object):
    def setupUi(self, StreamingMetadataOptionsPage):
        StreamingMetadataOptionsPage.setObjectName("StreamingMetadataOptionsPage")
        StreamingMetadataOptionsPage.resize(415, 200)
        self.verticalLayout = QtWidgets.QVBoxLayout(StreamingMetadataOptionsPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.spotify_groupbox = QtWidgets.QGroupBox(StreamingMetadataOptionsPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spotify_groupbox.sizePolicy().hasHeightForWidth())
        self.spotify_groupbox.setSizePolicy(sizePolicy)
        self.spotify_groupbox.setMinimumSize(QtCore.QSize(397, 0))
        self.spotify_groupbox.setObjectName("spotify_groupbox")
        self.gridlayout = QtWidgets.QGridLayout(self.spotify_groupbox)
        self.gridlayout.setSpacing(2)
        self.gridlayout.setObjectName("gridlayout")
        self.label_1 = QtWidgets.QLabel(self.spotify_groupbox)
        self.label_1.setObjectName("label_1")
        self.gridlayout.addWidget(self.label_1, 0, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.spotify_groupbox)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2, 2, 0, 1, 2)
        self.client_secret = QtWidgets.QLineEdit(self.spotify_groupbox)
        self.client_secret.setEchoMode(QtWidgets.QLineEdit.Password)
        self.client_secret.setObjectName("client_secret")
        self.gridlayout.addWidget(self.client_secret, 3, 0, 1, 1)
        self.client_id = QtWidgets.QLineEdit(self.spotify_groupbox)
        self.client_id.setObjectName("client_id")
        self.gridlayout.addWidget(self.client_id, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.spotify_groupbox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(StreamingMetadataOptionsPage)
        QtCore.QMetaObject.connectSlotsByName(StreamingMetadataOptionsPage)
        StreamingMetadataOptionsPage.setTabOrder(self.client_id, self.client_secret)

    def retranslateUi(self, StreamingMetadataOptionsPage):
        _translate = QtCore.QCoreApplication.translate
        self.spotify_groupbox.setTitle(_translate("StreamingMetadataOptionsPage", "Spotify"))
        self.label_1.setText(_translate("StreamingMetadataOptionsPage", "Spotify client ID:"))
        self.label_2.setText(_translate("StreamingMetadataOptionsPage", "Spotify client secret:"))
